2025/02/07 13:13:09 [notice] 22#22: signal process started
2025/02/07 13:50:53 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:55 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:55 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:55 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:56 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:56 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:56 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:56 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:56 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:57 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:57 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:57 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:57 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:58 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:58 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:58 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:58 [error] 14#14: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:59 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:59 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:50:59 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:00 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:00 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:00 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:00 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:01 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:01 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:01 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:02 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:02 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
2025/02/07 13:51:03 [error] 14#14: *45 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: www.aeminian.42.fr, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.5:9000", host: "localhost"
